class Constants:
    @staticmethod
    def getAllSymbols():
        symbolsDict = [
            {
                "symbol": "BTCUSDT",
                "description": "Bitcoin / Tether",
                "order": 0,
                "visibility": True
            },
            {
                "symbol": "ETHUSDT",
                "description": "Ethereum / Tether",
                "order": 1,
                "visibility": True
            },
            {
                "symbol": "ADAUSDT",
                "description": "Cardano / Tether",
                "order": 2,
                "visibility": True
            },
            {
                "symbol": "BNBUSDT",
                "description": "Binance Coin / Tether",
                "order": 3,
                "visibility": False
            },
            {
                "symbol": "SOLUSDT",
                "description": "Solana / Tether",
                "order": 4,
                "visibility": False
            },
            {
                "symbol": "MATICUSDT",
                "description": "Poligon / Tether",
                "order": 5,
                "visibility": False
            },
            {
                "symbol": "LTCUSDT",
                "description": "Litecoin / Tether",
                "order": 6,
                "visibility": False
            },
            {
                "symbol": "ATOMUSDT",
                "description": "Atom / Tether",
                "order": 7,
                "visibility": False
            },
            {
                "symbol": "DASHUSDT",
                "description": "Dash / Tether",
                "order": 8,
                "visibility": False
            },
            {
                "symbol": "EOSUSDT",
                "description": "EOS / Tether",
                "order": 9,
                "visibility": False
            },
        ]
        return symbolsDict

    @staticmethod
    def getCandleRankings():
        candleRankings = {
            "CDL_3LINESTRIKE_Bull": 1,
            "CDL_3LINESTRIKE_Bear": 2,
            "CDL_3BLACKCROWS_Bull": 3,
            "CDL_3BLACKCROWS_Bear": 3,
            "CDL_EVENINGSTAR_Bull": 4,
            "CDL_EVENINGSTAR_Bear": 4,
            "CDL_TASUKIGAP_Bull": 5,
            "CDL_TASUKIGAP_Bear": 5,
            "CDL_INVERTEDHAMMER_Bull": 6,
            "CDL_INVERTEDHAMMER_Bear": 6,
            "CDL_MATCHINGLOW_Bull": 7,
            "CDL_MATCHINGLOW_Bear": 7,
            "CDL_ABANDONEDBABY_Bull": 8,
            "CDL_ABANDONEDBABY_Bear": 8,
            "CDL_BREAKAWAY_Bull": 10,
            "CDL_BREAKAWAY_Bear": 10,
            "CDL_MORNINGSTAR_Bull": 12,
            "CDL_MORNINGSTAR_Bear": 12,
            "CDL_PIERCING_Bull": 13,
            "CDL_PIERCING_Bear": 13,
            "CDL_STICKSANDWICH_Bull": 14,
            "CDL_STICKSANDWICH_Bear": 14,
            "CDL_THRUSTING_Bull": 15,
            "CDL_THRUSTING_Bear": 15,
            "CDL_INNECK_Bull": 17,
            "CDL_INNECK_Bear": 17,
            "CDL_3INSIDE_Bull": 20,
            "CDL_3INSIDE_Bear": 56,
            "CDL_HOMINGPIGEON_Bull": 21,
            "CDL_HOMINGPIGEON_Bear": 21,
            "CDL_DARKCLOUDCOVER_Bull": 22,
            "CDL_DARKCLOUDCOVER_Bear": 22,
            "CDL_IDENTICAL3CROWS_Bull": 24,
            "CDL_IDENTICAL3CROWS_Bear": 24,
            "CDL_MORNINGDOJISTAR_Bull": 25,
            "CDL_MORNINGDOJISTAR_Bear": 25,
            "CDL_XSIDEGAP3METHODS_Bull": 27,
            "CDL_XSIDEGAP3METHODS_Bear": 26,
            "CDL_TRISTAR_Bull": 28,
            "CDL_TRISTAR_Bear": 76,
            "CDL_GAPSIDESIDEWHITE_Bull": 46,
            "CDL_GAPSIDESIDEWHITE_Bear": 29,
            "CDL_EVENINGDOJISTAR_Bull": 30,
            "CDL_EVENINGDOJISTAR_Bear": 30,
            "CDL_3WHITESOLDIERS_Bull": 32,
            "CDL_3WHITESOLDIERS_Bear": 32,
            "CDL_ONNECK_Bull": 33,
            "CDL_ONNECK_Bear": 33,
            "CDL_3OUTSIDE_Bull": 34,
            "CDL_3OUTSIDE_Bear": 39,
            "CDL_RICKSHAWMAN_Bull": 35,
            "CDL_RICKSHAWMAN_Bear": 35,
            "CDL_SEPARATINGLINES_Bull": 36,
            "CDL_SEPARATINGLINES_Bear": 40,
            "CDL_LONGLEGGEDDOJI_Bull": 37,
            "CDL_LONGLEGGEDDOJI_Bear": 37,
            "CDL_HARAMI_Bull": 38,
            "CDL_HARAMI_Bear": 72,
            "CDL_LADDERBOTTOM_Bull": 41,
            "CDL_LADDERBOTTOM_Bear": 41,
            "CDL_CLOSINGMARUBOZU_Bull": 70,
            "CDL_CLOSINGMARUBOZU_Bear": 43,
            "CDL_TAKURI_Bull": 47,
            "CDL_TAKURI_Bear": 47,
            "CDL_DOJISTAR_Bull": 49,
            "CDL_DOJISTAR_Bear": 51,
            "CDL_HARAMICROSS_Bull": 50,
            "CDL_HARAMICROSS_Bear": 80,
            "CDL_ADVANCEBLOCK_Bull": 54,
            "CDL_ADVANCEBLOCK_Bear": 54,
            "CDL_SHOOTINGSTAR_Bull": 55,
            "CDL_SHOOTINGSTAR_Bear": 55,
            "CDL_MARUBOZU_Bull": 71,
            "CDL_MARUBOZU_Bear": 57,
            "CDL_UNIQUE3RIVER_Bull": 60,
            "CDL_UNIQUE3RIVER_Bear": 60,
            "CDL_2CROWS_Bull": 61,
            "CDL_2CROWS_Bear": 61,
            "CDL_BELTHOLD_Bull": 62,
            "CDL_BELTHOLD_Bear": 63,
            "CDL_HAMMER_Bull": 65,
            "CDL_HAMMER_Bear": 65,
            "CDL_HIGHWAVE_Bull": 67,
            "CDL_HIGHWAVE_Bear": 67,
            "CDL_SPINNINGTOP_Bull": 69,
            "CDL_SPINNINGTOP_Bear": 73,
            "CDL_UPSIDEGAP2CROWS_Bull": 74,
            "CDL_UPSIDEGAP2CROWS_Bear": 74,
            "CDL_GRAVESTONEDOJI_Bull": 77,
            "CDL_GRAVESTONEDOJI_Bear": 77,
            "CDL_HIKKAKEMOD_Bull": 82,
            "CDL_HIKKAKEMOD_Bear": 81,
            "CDL_HIKKAKE_Bull": 85,
            "CDL_HIKKAKE_Bear": 83,
            "CDL_ENGULFING_Bull": 84,
            "CDL_ENGULFING_Bear": 91,
            "CDL_MATHOLD_Bull": 86,
            "CDL_MATHOLD_Bear": 86,
            "CDL_HANGINGMAN_Bull": 87,
            "CDL_HANGINGMAN_Bear": 87,
            "CDL_RISEFALL3METHODS_Bull": 94,
            "CDL_RISEFALL3METHODS_Bear": 89,
            "CDL_KICKING_Bull": 96,
            "CDL_KICKING_Bear": 102,
            "CDL_DRAGONFLYDOJI_Bull": 98,
            "CDL_DRAGONFLYDOJI_Bear": 98,
            "CDL_CONCEALBABYSWALL_Bull": 101,
            "CDL_CONCEALBABYSWALL_Bear": 101,
            "CDL_3STARSINSOUTH_Bull": 103,
            "CDL_3STARSINSOUTH_Bear": 103,
            "CDL_DOJI_10_0.1_Bull": 104,
            "CDL_DOJI_10_0.1_Bear": 104
        }
        return candleRankings
